ALTER TABLE analyses ADD COLUMN IF NOT EXISTS github_url TEXT;
ALTER TABLE analyses ADD COLUMN IF NOT EXISTS nodes JSONB;
ALTER TABLE analyses ADD COLUMN IF NOT EXISTS edges JSONB;
ALTER TABLE analyses ADD COLUMN IF NOT EXISTS metrics JSONB;
ALTER TABLE analyses ADD COLUMN IF NOT EXISTS error_message TEXT;
ALTER TABLE analyses ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
